AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  porteiro

  Sample SAM Template for porteiro
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15

Resources:
  LigarPorteiro:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/handlers/porteiro.startEC2Instance
      Runtime: nodejs24.x
      Architectures:
        - x86_64

      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(20 16 ? * MON-SAT *)

      Policies:
        - Statement:
            - Sid: StartEC2
              Effect: Allow
              Action:
                - ec2:StartInstances
              Resource: "*"
  DesligarPorteiro:
    Type: AWS::Serverless::Function
    Properties:S
      CodeUri: .
      Handler: src/handlers/porteiro.stopEC2Instance
      Runtime: nodejs24.x
      Architectures:
        - x86_64

      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(21 16 ? * MON-SAT *)

      Policies:
        - Statement:
            - Sid: StopEC2
              Effect: Allow
              Action:
                - ec2:StopInstances
              Resource: "*"